var products = [
    {
        "id": "1",
        "name": "Quạt lửng Senko",
        "description": "Quạt lửng Senko L1638 thiết kế đẹp mắt, tùy chỉnh được chiều cao quạt, làm mát với 3 cánh quạt có công suất 47W, vận hành êm ái với động cơ bạc thau được làm từ chất liệu 100% dây đồng, bền bỉ, ít hao mòn.",
        "price": "299.000",
        "image": "quatlung_2.png",
        "brand": "Senko",
        "type": "Quạt lửng",
        "power": "47",
        "speed": "3",
        "highlight": "Quạt lửng Senko L1638 thiết kế đẹp mắt, tùy chỉnh được chiều cao quạt, làm mát với 3 cánh quạt có công suất 47W, vận hành êm ái với động cơ bạc thau được làm từ chất liệu 100% dây đồng, bền bỉ, ít hao mòn.",
        "origin": "Việt Nam"
    },
    {
        "id": "2",
        "name": "Quạt hơi nước Coex cao cấp",
        "description": "Công suất 130W tạo lưu lượng gió 5000 m³\/h, phù hợp với diện tích làm mát 35 - 50 m2.\r\nĐa chức năng LÀM MÁT - TẠO ẨM - TẠO ION LÀM SẠCH KHÔNG KHÍ\r\n3 tốc độ gió bình thường, tự nhiên và chế độ gió nhẹ khi ngủ ",
        "price": "2.390.000",
        "image": "hoinuoc_2.png",
        "brand": "Coex",
        "type": "Quạt hơi nước",
        "power": "139",
        "speed": "3",
        "highlight": "Thang đo mực nước, tiện cho bạn theo dõi lượng nước trong bình\r\nTrang bị 2 cục đá khô giúp giảm nhiệt độ đáng kể và tăng hiệu quả làm mát\r\nTiết kiệm điện gấp 10 lần so với điều hòa không khí",
        "origin": "Trung Quốc"
    },
    {
        "id": "4",
        "name": "Quạt lửng Senko thế hệ mới",
        "description": "- Quạt lửng thiết kế đơn giản, các chi tiết bên ngoài bằng nhựa dễ dàng vệ sinh, khối lượng 4.1 kg nhẹ nhàng khi di chuyển và tháo lắp. 3 cánh quạt đường kính 39 cm tạo luồng gió mát rộng nhanh chóng.\r\nThay đổi chiều cao trong khoảng 75.6 đến 91.5 cm phù hợp với nhu cầu và không gian sử dụng.",
        "price": "390.000",
        "image": "quattrang.png",
        "brand": "Senko",
        "type": "Quạt lửng",
        "power": "35",
        "speed": "3",
        "highlight": "Quạt lửng Senko L1638 thiết kế đẹp mắt, tùy chỉnh được chiều cao quạt, làm mát với 3 cánh quạt có công suất 47W, vận hành êm ái với động cơ bạc thau được làm từ chất liệu 100% dây đồng, bền bỉ, ít hao mòn.",
        "origin": "Vệt Nam"
    },
    {
        "id": "5",
        "name": "Quạt hơi nước Coex",
        "description": "Công suất 150W tạo lưu lượng gió 3000 m³\/h, phù hợp với phòng 30-40m2.Độ ồn dưới mức 55dB tương đương tiếng văn phòng làm việc. Tấm làm mát chất liệu gỗ sồi ép, làm mát hiệu quả và bảo vệ môi trường.",
        "price": "3.290.000",
        "image": "quathoinuoc_1.jpg",
        "brand": "Coex",
        "type": "Quạt hơi nước",
        "power": "150",
        "speed": "3",
        "highlight": "Bảng điều khiển nút nhấn và núm xoay đơn giản các chức năng tốc độ gió, làm mát, đảo gióTặng kèm 1 cục đá khô giúp giảm nhiệt độ đáng kể và tăng hiệu quả làm mátTiết kiệm điện gấp 10 lần so với điều hòa không khí",
        "origin": "Trung Quốc"
    },
    {
        "id": "6",
        "name": "Quạt lửng Điện cơ",
        "description": "Quạt lửng Điện cơ sẽ là một giải pháp vừa hiệu quả vừa tiết kiệm trong những ngày hè oi bức. Sản phẩm này sẽ làm không gian nhà bạn trở nên dịu mát và dễ chịu.",
        "price": "469.000",
        "image": "quattrang.jpg",
        "brand": "Vinawind - Ðiện cơ",
        "type": "Quạt lửng",
        "power": "48",
        "speed": "3",
        "highlight": "Phím bấm 3 tốc độ\r\nNúm rút chuyển hướng",
        "origin": "Việt Nam"
    },
    {
        "id": "7",
        "name": "Quạt lửng Asia Turbo One",
        "description": "Mùa hè mang đến những đợt nắng gay gắt khiến đầu óc căng thẳng, tinh thần làm việc cũng giảm sút đáng kể. Thời điểm này thì chiếc quạt điện chính là người bạn đồng hành tốt nhất cho bạn và cả gia đình.",
        "price": "529.000",
        "image": "quatlung_3.png",
        "brand": "Asia",
        "type": "Quạt lửng",
        "power": "54",
        "speed": "3",
        "highlight": "Lượng gió tải rộng và tốc độ gió cực nhanh lên đến 5.1 m\/s,gấp 1.5 lần quạt thường\r\nMotor hoạt động bền bỉ với công nghệ Dual Cooling System (Công nghệ làm mát kép)",
        "origin": "Việt Nam"
    },
    {
        "id": "8",
        "name": "Quạt trần 4 cánh Panasonic",
        "description": "Nhờ được áp dụng công nghệ thiết kế tiên tiến, mô tơ và các cánh của quạt trần Panasonic F-56XPG được tối ưu hóa cho hiệu suất hoạt động cao, độ ồn thấp và tiết kiệm điện. Các cánh quạt được thiết kế đặc biệt cho lượng gió tản đều, rộng mà không chém vào không khí do đó không tạo ra tiếng ồn.",
        "price": "2.790.000",
        "image": "qut-trn-4-canh-panasonic-f-56xpg-den-co-diu-khin_8c414d1e.jpg",
        "brand": "Panasonic",
        "type": "Quạt trần",
        "power": "59",
        "speed": "3",
        "highlight": "Dây nối an toàn, công tắc  ngắt an toàn giúp bảo vệ động cơ\r\n3 cấp độ gió, công suất 59W",
        "origin": "Malaysia"
    },
    {
        "id": "9",
        "name": "Quạt trần 5 cánh Panasonic",
        "description": "Công suất 57W (motor: 37W, đèn: 20W)\r\nĐộng cơ DC tiết kiệm điện\r\nTích hợp đèn LED có thể thay đổi theo 4 cấp độ màu sắc ánh sáng\r\n03 cấp độ an toàn (khóa cánh an toàn, dây an toàn, công tắc an toàn) Chức năng tạo gió tự nhiên (1\/f Yuragi)",
        "price": "9.590.000",
        "image": "qut-trn-5-canh-panasonic-f-60ufn-den-ledco-diu-khin---malaysia_16852b8b.jpg",
        "brand": "Panasonic",
        "type": "Quạt trần",
        "power": "57",
        "speed": "3",
        "highlight": "Đường kính cánh 150cm Chiều dài ti 28.8cm \r\nĐộng cơ DC tiết kiệm điện \r\nTích hợp đèn LED có thể thay đổi theo 4 cấp độ màu sắc ánh sáng \r\n03 cấp độ an toàn",
        "origin": "Malaysia"
    },
    {
        "id": "12",
        "name": "Quạt hơi nước Coex (Điều khiển từ xa)",
        "description": "Quạt điều hòa Coex có động cơ làm bằng đồng nguyên chất, giúp máy hoạt động bền bỉ. Thân máy làm bằng nhựa ABS bền đẹp, bề mặt sáng bóng, hạn chế bám bụi, dễ dàng vệ sinh. Sản phẩm có kiểu dáng sang trọng, kích thước nhỏ gọn, tiết kiệm diện tích, phù hợp với nhiều không gian khác nhau.",
        "price": "2.199.999",
        "image": "quat-dieu-hoa-coex-ca-7124a-dieu-khien-tu-xa_6b6ef392.png",
        "brand": "Coex",
        "type": "Quạt hơi nước",
        "power": "100",
        "speed": "3",
        "highlight": "Công suất 100W tạo lưu lượng gió 3200 m³\/h, phù hợp với diện tích làm mát 30 - 40 m2. \r\nĐa chức năng LÀM MÁT - TẠO ẨM - TẠO ION LÀM SẠCH KHÔNG KHÍ \r\n3 tốc độ gió bình thường, tự nhiên và chế độ gió nhẹ khi ngủ  \r\n3 mặt lấy gió, lưu lượng gió cực lớn  ",
        "origin": "Trung Quốc"
    },
    {
        "id": "13",
        "name": "Quạt trần 5 cánh Panasonic có điều khiển-ti30-Malaysia",
        "description": "Quạt Panasonic có thiết kế hiện đại, màu sắc trang nhã phù hợp với nhiều không gian lớn: phòng khách, phòng ngủ, phòng làm việc, quán ăn hay showroom,... \r\nThiết kế 5 cánh quạt có đường kính 150 cm tạo ra làn gió mát trải rộng giúp xua tan không khí oi bức trong phòng nhanh chóng. ",
        "price": "4.990.000",
        "image": "qut-trn-3-canh-coex-ccf---7111_40889730.jpg",
        "brand": "Panasonic",
        "type": "Quạt trần",
        "power": "76",
        "speed": "5",
        "highlight": "Quạt Panasonic có thiết kế hiện đại, màu sắc trang nhã phù hợp với nhiều không gian lớn: phòng khách, phòng ngủ, phòng làm việc, quán ăn hay showroom,... ",
        "origin": "Malaysia"
    },
    {
        "id": "16",
        "name": "Quạt hơi nước Coex tạo ẩm-Ion",
        "description": "GIẢI PHÁP LÀM MÁT TỐI ƯU\r\nQuạt điều hòa Coex hoạt động dựa trên nguyên lý bay hơi nước tự nhiên. Không khí nóng sau khi đi qua tấm làm mát sẽ cho ra luồng gió mát . Dựa trên nguyên lý đó, sản phẩm có khả năng làm mát trên diện rộng, tiết kiệm điện năng hiệu quả hơn các sản phẩm thông thường.Đặc biệt, Quạt điều hòa Coex làm mát hiệu quả với những không gian mà quạt mát thông thường hay điều hòa không thể phát huy hiệu quả làm mát.",
        "price": "2.999.000",
        "image": "qut-diu-hoa-coex-ca-7121_736c3782.jpg",
        "brand": "Coex",
        "type": "Quạt hơi nước",
        "power": "200",
        "speed": "3",
        "highlight": "Công suất 200W tạo lưu lượng gió 5000 m³\/h, phù hợp với diện tích làm mát 35 - 50 m2.\r\nĐa chức năng LÀM MÁT - TẠO ẨM - TẠO ION LÀM SẠCH KHÔNG KHÍ\r\nĐộ ồn thấp dưới mức ≤65dB không gây tiếng ồn \r\nTấm làm mát chất liệu gỗ sồi ép, làm mát hiệu quả và bảo vệ môi trường.",
        "origin": "Trung Quốc"
    },
    {
        "id": "17",
        "name": "Quạt hơi nước Sunhouse",
        "description": "Máy làm mát không khí SUNHOUSE hoạt động dựa trên nguyên lý bay hơi nước tự nhiên. Không khí nóng sau khi đi qua tấm làm mát sẽ cho ra luồng gió mát . Dựa trên nguyên lý đó, sản phẩm có khả năng làm mát trên diện rộng, tiết kiệm điện năng hiệu quả hơn các sản phẩm thông thường.",
        "price": "1.990.000",
        "image": "quat-dieu-hoa-sunhouse-shd7734-05I3uT.png",
        "brand": "Sunhouse",
        "type": "Quạt hơi nước",
        "power": "150",
        "speed": "3",
        "highlight": "Giải pháp làm mát tối ưu và tiết kiệm điện cho không gian mở (lên đến 35m2)\r\nGió mát tự nhiên, thân thiện với sức khỏe\r\n3 mặt lấy gió, lưu lượng gió cực lớn – lên đến 4.000m3\/giờ",
        "origin": "Trung Quốc"
    },
    {
        "id": "18",
        "name": "Quạt trần 3 cánh Coex CCF",
        "description": "Quạt trần 3 cánh Coex CCF có thiết kế tinh tế với màu trắng viền vàng thời trang, phong cách vừa cổ điển, vừa hiện đại. Quạt không chỉ làm mát mà còn giúp trang trí nội thất cho căn phòng. Đặc biệt, quạt trần COEX có khuyến mại kèm MÓC TREO áp trần, thao tác lắp đặt đơn giản chỉ cần bắn thêm VÍT NỞ là sử dụng được ngay. Đây là ưu điểm hơn hẳn các nhãn khác cùng phân khúc giá thành.",
        "price": "1.990.000",
        "image": "qut-trn-3-canh-coex-ccf---7112_847867da.jpg",
        "brand": "Coex",
        "type": "Quạt trần",
        "power": "80",
        "speed": "5",
        "highlight": "Công suât 80W luồng gió mạnh mẽ và phân bố đều.\r\nMotor 100% lõi đồng, tăng tuổi thọ, vận hành êm ái.\r\n3 cánh quạt đường kính quạt 140cm, sải cánh lớn, luồng gió lan tỏa trên phạm vi rộng và phân tán gió đều .\r\n5 tốc độ gió đáp ứng nhu cầu làm mát khác nhau.\r\nDây an toàn đề phòng cánh quạt và motor bị rơi.\r\nTự ngắt bảo vệ động cơ khi quá nhiệt, quá nóng.",
        "origin": "Trung Quốc"
    },
    {
        "id": "19",
        "name": "Quạt trần 3 cánh Coex CCF (Điều khiển từ xa)",
        "description": "Quạt trần 3 cánh Coex CCF  có thiết kế tinh tế với màu trắng thời trang, phong cách vừa cổ điển, vừa hiện đại. Quạt không chỉ làm mát mà còn giúp trang trí nội thất cho căn phòng. Đặc biệt, quạt trần COEX có khuyến mại kèm MÓC TREO áp trần, thao tác lắp đặt đơn giản chỉ cần bắn thêm VÍT NỞ là sử dụng được ngay. Đây là ưu điểm hơn hẳn các nhãn khác cùng phân khúc giá thành.",
        "price": "2.999.000",
        "image": "quat-tran-3-canh-coex-ccf---7113a-co-dieu-khien_87629938.png",
        "brand": "Coex",
        "type": "Quạt trần",
        "power": "90",
        "speed": "5",
        "highlight": "Công suât 90W luồng gió mạnh mẽ và phân bố đều.\r\nMotor 100% lõi đồng, tăng tuổi thọ, vận hành êm ái.\r\n3 cánh quạt đường kính quạt 150cm, sải cánh lớn, luồng gió lan tỏa trên phạm vi rộng và phân tán gió đều .\r\n5 tốc độ gió đáp ứng nhu cầu làm mát khác nhau.",
        "origin": "Trung Quốc"
    },
    {
        "id": "20",
        "name": "Quạt lửng DC 360 độ Mitsubishi",
        "description": "Quạt lửng cao cấp Mitsubishi R12A-DA với 7 cánh sải rộng 30cm cho luồng gió rộng. Quạt quay trái phải và đảo chiều giúp làn gió lan tỏa ra không gian rộng nhanh chóng đem lại bầu không khí mát mẻ dễ chịu. Ngoài ra, Tính năng kép: Kết hợp với chế độ làm mát và lưu thông không khí đem đến sự thoải mái cho không gian sống của bạn.",
        "price": "6.890.000",
        "image": "quat-cay-hitachi-lf-d6rcwm-mau-trang---co-dieu-khien_d81977ea.png",
        "brand": "Mitsubishi",
        "type": "Quạt lửng",
        "power": "30",
        "speed": "3",
        "highlight": "DC Motor hoạt động yên tĩnh và tiết kiệm năng lượng.\r\nMức tiêu thụ năng lượng tối đa chỉ 13W.\r\nĐiều chỉnh công suất gió lên tới 5 cấp.\r\nĐiều chỉnh độ cao thành 2 mức (102 cm và 58 cm).",
        "origin": "Thái Lan"
    },
    {
        "id": "21",
        "name": "Quạt lửng tích điện Coex",
        "description": "Quạt sạc Quạt tích điện Coex có thiết kế nhỏ gọn, sử dụng pin sạc chất lượng cao, hoạt động liên tục trong 5-16 giờ (tùy tốc độ) giúp làm mát hiệu quả cho cả gia đình bạn trong những lúc mất điện. Sản phẩm có thể tùy chỉnh độ cao linh hoạt và được trang bị đến 3 tốc độ gió THẤP\/TRUNG\/CAO đáp ứng nhu cầu làm mát khác nhau, sử dụng phù hợp cho cả trẻ nhỏ, người già có hệ hô hấp yếu.",
        "price": "1.390.000",
        "image": "quat-tich-dien-coex---cf-7114r_eb554245.png",
        "brand": "Coex",
        "type": "Quạt lửng",
        "power": "24",
        "speed": "3",
        "highlight": "Quay đảo chiều, gió tản đều.Thời gian sạc đầy 12 - 15 giờ.Dung lượng pin lớn, hoạt động liên tục trong 5 - 16 giờ tùy tốc độTích hợp đèn ngủ 2 trong 1.Động cơ bền – Vận hành êm ái.Thiết kế nhỏ gọn, làm mát mọi lúc mọi nơi.",
        "origin": "Trung Quốc"
    },
    {
        "id": "22",
        "name": "Quạt hơi nước Coex tạo ẩm cao cấp",
        "description": "Quạt điều hoà Coex dễ dàng di chuyển với bánh xe, làm mát hiệu quả cho không gian phòng từ 45 - 55m2, dễ dàng điều chỉnh tốc độ gió bằng núm xoay, trang bị công nghệ diệt khuẩn Ag+ cho không khí tươi mát, tốt cho sức khỏe.",
        "price": "1.677.000",
        "image": "qut-diu-hoa-coex-ca-7121_16194536.png",
        "brand": "Coex",
        "type": "Quạt hơi nước",
        "power": "175",
        "speed": "3",
        "highlight": "Thiết kế hiện đại, bình chứa nước 72 lít, có bánh xe di chuyển dễ dàng.\r\nCông suất 175W phù hợp làm mát cho phòng từ 45 - 55m2.\r\nĐi kèm 2 đá khô hỗ trợ làm mát nhanh chóng.\r\nThương hiệu Daikiosan - Việt Nam, sản xuất tại Trung Quốc.",
        "origin": "Trung Quốc"
    },
    {
        "id": "23",
        "name": "Quạt lửng Hatari HT-điều khiển-Thailand",
        "description": "Nổi bật bởi khả năng làm mát nhanh, tản gió mạnh, động cơ bạc động hoạt đông êm ái, bền bỉ cùng thời gian, trang bị điều khiển từ xa thông minh, sản xuất tại Thái Lan, độ bền cao, quạt lửng Hatari HT chính là sản phẩm mà bạn không thể bỏ lỡ trong mùa hè này.\r\nCùng Hatari tìm hiểu chiếc quạt lửng đáng mua này nhé!",
        "price": "1.299.000",
        "image": "quat-lung-hatari-ht-s16r2-dieu-khien-thailand_f3c7dc76.png",
        "brand": "Hatari",
        "type": "Quạt lửng",
        "power": "50",
        "speed": "3",
        "highlight": "Điều chỉnh độ cao dễ dàng.\r\nCó đèn giúp người dùng dễ dàng sử dụng quạt vào ban đêm.\r\nAn toàn với sức khỏe người dùng, thân thiện với môi trường.",
        "origin": "Thái Lan"
    }
];