var products = [
    {
        "id": "2",
        "name": "Quạt hơi nước Coex cao cấp",
        "description": "Công suất 130W tạo lưu lượng gió 5000 m³\/h, phù hợp với diện tích làm mát 35 - 50 m2.\r\nĐa chức năng LÀM MÁT - TẠO ẨM - TẠO ION LÀM SẠCH KHÔNG KHÍ\r\n3 tốc độ gió bình thường, tự nhiên và chế độ gió nhẹ khi ngủ ",
        "price": "2.390.000",
        "image": "hoinuoc_2.png",
        "brand": "Coex",
        "type": "Quạt hơi nước",
        "power": "139",
        "speed": "3",
        "highlight": "Thang đo mực nước, tiện cho bạn theo dõi lượng nước trong bình\r\nTrang bị 2 cục đá khô giúp giảm nhiệt độ đáng kể và tăng hiệu quả làm mát\r\nTiết kiệm điện gấp 10 lần so với điều hòa không khí",
        "origin": "Trung Quốc"
    },
    {
        "id": "4",
        "name": "Quạt lửng Senko thế hệ mới",
        "description": "- Quạt lửng thiết kế đơn giản, các chi tiết bên ngoài bằng nhựa dễ dàng vệ sinh, khối lượng 4.1 kg nhẹ nhàng khi di chuyển và tháo lắp. 3 cánh quạt đường kính 39 cm tạo luồng gió mát rộng nhanh chóng.\r\nThay đổi chiều cao trong khoảng 75.6 đến 91.5 cm phù hợp với nhu cầu và không gian sử dụng.",
        "price": "399.000",
        "image": "quattrang.png",
        "brand": "Senko",
        "type": "Quạt lửng",
        "power": "35",
        "speed": "3",
        "highlight": "Chất lượng",
        "origin": "Vệt Nam"
    },
    {
        "id": "5",
        "name": "Quạt hơi nước Coex",
        "description": "Công suất 150W tạo lưu lượng gió 3000 m³\/h, phù hợp với phòng 30-40m2.Độ ồn dưới mức 55dB tương đương tiếng văn phòng làm việc. Tấm làm mát chất liệu gỗ sồi ép, làm mát hiệu quả và bảo vệ môi trường.",
        "price": "3.290.000",
        "image": "quathoinuoc_1.jpg",
        "brand": "Coex",
        "type": "Quạt hơi nước",
        "power": "150",
        "speed": "3",
        "highlight": "Bảng điều khiển nút nhấn và núm xoay đơn giản các chức năng tốc độ gió, làm mát, đảo gióTặng kèm 1 cục đá khô giúp giảm nhiệt độ đáng kể và tăng hiệu quả làm mátTiết kiệm điện gấp 10 lần so với điều hòa không khí",
        "origin": "Trung Quốc"
    },
    {
        "id": "6",
        "name": "Quạt lửng Điện cơ",
        "description": "Quạt lửng Điện cơ sẽ là một giải pháp vừa hiệu quả vừa tiết kiệm trong những ngày hè oi bức. Sản phẩm này sẽ làm không gian nhà bạn trở nên dịu mát và dễ chịu.",
        "price": "469.000",
        "image": "quattrang.jpg",
        "brand": "Vinawind - Ðiện cơ",
        "type": "Quạt lửng",
        "power": "48",
        "speed": "3",
        "highlight": "Phím bấm 3 tốc độ\r\nNúm rút chuyển hướng",
        "origin": "Việt Nam"
    },
    {
        "id": "7",
        "name": "Quạt lửng Asia Turbo One",
        "description": "Mùa hè mang đến những đợt nắng gay gắt khiến đầu óc căng thẳng, tinh thần làm việc cũng giảm sút đáng kể. Thời điểm này thì chiếc quạt điện chính là người bạn đồng hành tốt nhất cho bạn và cả gia đình.",
        "price": "529.000",
        "image": "quatlung_3.png",
        "brand": "Asia",
        "type": "Quạt lửng",
        "power": "54",
        "speed": "3",
        "highlight": "Lượng gió tải rộng và tốc độ gió cực nhanh lên đến 5.1 m\/s,gấp 1.5 lần quạt thường\r\nMotor hoạt động bền bỉ với công nghệ Dual Cooling System (Công nghệ làm mát kép)",
        "origin": "Việt Nam"
    },
    {
        "id": "8",
        "name": "Quạt trần 4 cánh Panasonic",
        "description": "Nhờ được áp dụng công nghệ thiết kế tiên tiến, mô tơ và các cánh của quạt trần Panasonic F-56XPG được tối ưu hóa cho hiệu suất hoạt động cao, độ ồn thấp và tiết kiệm điện. Các cánh quạt được thiết kế đặc biệt cho lượng gió tản đều, rộng mà không chém vào không khí do đó không tạo ra tiếng ồn.",
        "price": "2.790.000",
        "image": "qut-trn-4-canh-panasonic-f-56xpg-den-co-diu-khin_8c414d1e.jpg",
        "brand": "Panasonic",
        "type": "Quạt trần",
        "power": "59",
        "speed": "3",
        "highlight": "Dây nối an toàn, công tắc  ngắt an toàn giúp bảo vệ động cơ\r\n3 cấp độ gió, công suất 59W",
        "origin": "Malaysia"
    },
    {
        "id": "9",
        "name": "Quạt trần 5 cánh Panasonic",
        "description": "Công suất 57W (motor: 37W, đèn: 20W)\r\nĐộng cơ DC tiết kiệm điện\r\nTích hợp đèn LED có thể thay đổi theo 4 cấp độ màu sắc ánh sáng\r\n03 cấp độ an toàn (khóa cánh an toàn, dây an toàn, công tắc an toàn) Chức năng tạo gió tự nhiên (1\/f Yuragi)",
        "price": "9.590.000",
        "image": "qut-trn-5-canh-panasonic-f-60ufn-den-ledco-diu-khin---malaysia_16852b8b.jpg",
        "brand": "Panasonic",
        "type": "Quạt trần",
        "power": "57",
        "speed": "3",
        "highlight": "Đường kính cánh 150cm Chiều dài ti 28.8cm \r\nĐộng cơ DC tiết kiệm điện \r\nTích hợp đèn LED có thể thay đổi theo 4 cấp độ màu sắc ánh sáng \r\n03 cấp độ an toàn",
        "origin": "Malaysia"
    },
    {
        "id": "12",
        "name": "Quạt hơi nước Coex (Điều khiển từ xa)",
        "description": "Quạt điều hòa Coex có động cơ làm bằng đồng nguyên chất, giúp máy hoạt động bền bỉ. Thân máy làm bằng nhựa ABS bền đẹp, bề mặt sáng bóng, hạn chế bám bụi, dễ dàng vệ sinh. Sản phẩm có kiểu dáng sang trọng, kích thước nhỏ gọn, tiết kiệm diện tích, phù hợp với nhiều không gian khác nhau.",
        "price": "2.199.999",
        "image": "quat-dieu-hoa-coex-ca-7124a-dieu-khien-tu-xa_6b6ef392.png",
        "brand": "Coex",
        "type": "Quạt hơi nước",
        "power": "100",
        "speed": "3",
        "highlight": "Công suất 100W tạo lưu lượng gió 3200 m³\/h, phù hợp với diện tích làm mát 30 - 40 m2. \r\nĐa chức năng LÀM MÁT - TẠO ẨM - TẠO ION LÀM SẠCH KHÔNG KHÍ \r\n3 tốc độ gió bình thường, tự nhiên và chế độ gió nhẹ khi ngủ  \r\n3 mặt lấy gió, lưu lượng gió cực lớn  ",
        "origin": "Trung Quốc"
    },
    {
        "id": "13",
        "name": "Quạt trần 5 cánh Panasonic có điều khiển-ti30-Malaysia",
        "description": "Quạt Panasonic có thiết kế hiện đại, màu sắc trang nhã phù hợp với nhiều không gian lớn: phòng khách, phòng ngủ, phòng làm việc, quán ăn hay showroom,... \r\nThiết kế 5 cánh quạt có đường kính 150 cm tạo ra làn gió mát trải rộng giúp xua tan không khí oi bức trong phòng nhanh chóng. ",
        "price": "4.990.000",
        "image": "qut-trn-3-canh-coex-ccf---7111_40889730.jpg",
        "brand": "Panasonic",
        "type": "Quạt trần",
        "power": "76",
        "speed": "5",
        "highlight": "Quạt Panasonic có thiết kế hiện đại, màu sắc trang nhã phù hợp với nhiều không gian lớn: phòng khách, phòng ngủ, phòng làm việc, quán ăn hay showroom,... ",
        "origin": "Malaysia"
    },
    {
        "id": "16",
        "name": "Quạt lửng Midea",
        "description": "Quạt lửng với 3 cánh quạt đường kính 40 cm tạo luồng gió trải rộng, làm mát khắp diện tích phòng.\r\nCái quạt có lồng quạt chắc chắn, nan quạt đan khít an toàn khi tiếp xúc gần; thiết kế có thể tháo rời vệ sinh thuận tiện.\r\n\r\n3 tốc độ gió điều khiển bằng núm vặn phía trên cụm motor.\r\nĐộng cơ bạc thau vận hành với công suất 36 W.",
        "price": "555.000",
        "image": "quat-lung-midea-fts4017vd-5XUrrb.jpg",
        "brand": "Midea",
        "type": "Quạt lửng",
        "power": "36",
        "speed": "3",
        "highlight": "Quạt lửng 3 cánh, công suất 36W.3 mức gió, có tút năng xoay trái phải. Điều chỉnh chiều cao dễ dàng",
        "origin": "Trung Quốc"
    },
    {
        "id": "17",
        "name": "Quạt điều hòa cơ Boss-ThaiLand",
        "description": "Quạt điều hòa Boss S102 có kiểu dáng bắt mắt, chất liệu nhựa ABS chắc chắn, màu sắc đơn giản nhưng vô cùng trang nhã, tiện lợi khi chuyển khắp nơi.Boss S102 với khả năng làm sạch không khí, cung cấp độ ẩm, giúp ngôi nhà bạn trở nên sach khuẩn, trong lành.",
        "price": "3.999.000",
        "image": "-L4V5yx.png",
        "brand": "Boss",
        "type": "Quạt hơi nước",
        "power": "100",
        "speed": "3",
        "highlight": "Quạt điều hòa có lưu lượng gió 1500 m3\/h và công suất 100 W, thích hợp diện tích 15 – 20 m2.Độ ồn từ 50dB - 60dB. Đảo gió 4 chiều, giúp tăng tốc độ làm mát.Dung tích bình chứa nước 14 lít, dùng liên tục trong 7 tiếng.Có thang đo hiển thị mực nước. Bảng điều khiển nút nhấn có màn hình hiển thị dễ dùng.Hẹn giờ tắt 8 tiếng, thuận tiện với giấc ngủ về đêm.Remote điều khiển từ xa tiện dụng.",
        "origin": "Thái Lan"
    },
    {
        "id": "18",
        "name": "Quạt cây 7 cánh động cơ DC Hitachi",
        "description": "Hitachi gồm 2 màu: trắng và xám để lựa chọn. Quạt cây sử dụng nguồn điện 220V, công suất 24W cùng động cơ DC chạy bền bỉ, êm ái, tiết kiệm điện và cho lưu lượng gió lớn 50.02 m3\/phút.Quạt điện thông minh Hitachi trang bi điều khiển từ xa điều chỉnh 24 tốc độ gió và 3 chế độ gió: Gió tự nhiên, gió ngủ và gió AI.\r\nChế độ gió AI sẽ tự động điều chỉnh lượng gió theo nhiệt độ môi trường.",
        "price": "890.000",
        "image": "quat-cay-hitachi-lf-d6rcwm-mau-trang---co-dieu-khien_d81977ea.png",
        "brand": "Hitachi",
        "type": "Quạt lửng",
        "power": "24",
        "speed": "3",
        "highlight": "Thiết kế hiện đại, phù hợp với nhiều không gian nhà khác nhau.\r\nThuận tiện, dễ sử dụng, phù hợp với mọi lứa tuổi.\r\nCó điều khiển từ xa, cho người sử dụng có thể điều chỉnh được quạt dễ dàng.",
        "origin": "Trung Quốc"
    },
    {
        "id": "19",
        "name": "Quạt hơi nước Coex 7212",
        "description": "Quạt điều hòa Coex hoạt động dựa trên nguyên lý bay hơi nước tự nhiên. Không khí nóng sau khi đi qua tấm làm mát sẽ cho ra luồng gió mát . Dựa trên nguyên lý đó, sản phẩm có khả năng làm mát trên diện rộng, tiết kiệm điện năng hiệu quả hơn các sản phẩm thông thường.Đặc biệt, Quạt điều hòa Coex làm mát hiệu quả với những không gian mà quạt mát thông thường hay điều hòa không thể phát huy hiệu quả làm mát.",
        "price": "2.990.000",
        "image": "qut-diu-hoa-coex-ca-7121_16194536.png",
        "brand": "Coex",
        "type": "Quạt hơi nước",
        "power": "200",
        "speed": "5",
        "highlight": "Công suất 200W tạo lưu lượng gió 5000 m³\/h, phù hợp với diện tích làm mát 35 - 50 m2.\r\nĐa chức năng LÀM MÁT - TẠO ẨM - TẠO ION LÀM SẠCH KHÔNG KHÍ\r\nĐộ ồn thấp dưới mức ≤65dB không gây tiếng ồn \r\nTấm làm mát chất liệu gỗ sồi ép, làm mát hiệu quả và bảo vệ môi trường.\r\n3 tốc độ gió bình thường, tự nhiên và chế độ gió nhẹ khi ngủ \r\nBảng điều khiển nút nhấn và núm xoay đơn giản các chức năng tốc độ gió, làm mát",
        "origin": "Trung Quốc"
    },
    {
        "id": "20",
        "name": "Quạt lửng Điện cơ",
        "description": "Quạt lửng Điện cơ có thể dễ dàng điều chỉnh độ cao bằng cách vặn vít hãm để nâng hạ ống rút và hướng quay bằng nút rút. Ngoài ra, bạn có thể tùy ý điều chỉnh góc gục đầu quạt, giúp làn gió mát tản đều khắp phòng.",
        "price": "469.000",
        "image": "quat-lung-dien-co-qdm400-co-dk-5976WK.jpg",
        "brand": "Vinawind",
        "type": "Quạt lửng",
        "power": "48",
        "speed": "3",
        "highlight": "Phím bấm 3 tốc độ. Núm rút chuyển hướng. Cơ cấu chuyển hướng kép. Điều khiển tuỳ ý góc gục đầu quạt",
        "origin": "Việt Nam"
    },
    {
        "id": "21",
        "name": "Quạt hơi nước điện tử Kangaroo",
        "description": "Quạt điều hòa Kangaroo kết cấu chắc chắn, cứng cáp với 2 màu nâu trắng. Công suất lớn 200 W, hoạt động hiệu quả với phạm vi làm mát tới 50 - 65 m². Bên dưới thân quạt thiết kế 4 bánh xe nhỏ cho việc di chuyển, bảo quản quạt linh hoạt mà không cần khiêng vác nặng nề.",
        "price": "3.900.000",
        "image": "qut-diu-hoa-coex-ca-7121_736c3782.jpg",
        "brand": "Kangaroo",
        "type": "Quạt hơi nước",
        "power": "200",
        "speed": "3",
        "highlight": "Hoạt động với công suất 200 W, tạo lưu lượng gió 10000 m3\/h, phạm vi làm mát lớn từ 50 - 65 m2.Dung tích bình chứa lớn 108 lít, thời gian sử dụng hơn 16 tiếng.Thang đo hiển thị mực nước, tiện quan sát và châm nước.Bảng điều khiển hiện đại, tùy chỉnh các chức năng.Điều khiển từ xa tùy chỉnh chức năng không cần lại gần.",
        "origin": "Trung Quốc"
    },
    {
        "id": "22",
        "name": "Quạt trần 5 cánh Panasonic",
        "description": "Quạt trần Panasonic F-60WWK thiết kế tinh tế, hiện đại, sử dụng động cơ bạc đạn có độ bền cao, công suất hoạt động 76W, 5 cánh quạt làm mát hiệu quả cho không gian lớn.",
        "price": "4.990.000",
        "image": "quat-tran-3-canh-coex-ccf---7113a-co-dieu-khien_87629938.png",
        "brand": "Panasonic",
        "type": "Quạt trần",
        "power": "76",
        "speed": "5",
        "highlight": "Thiết kế 5 cánh quạt có đường kính 150 cm tạo ra làn gió mát trải rộng giúp xua tan không khí oi bức trong phòng nhanh chóng. \r\nMẫu quạt trần này được tích hợp động cơ bạc đạn sử dụng bền bỉ, vòng bi trơn bôi vĩnh viễn cho thiết bị hoạt động êm ái, hạn chế tiếng ồn, không ảnh hưởng đến hoạt động sinh hoạt thường nhật của gia đình.",
        "origin": "Malaysia"
    }
];